import { Cairo } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import 'bootstrap/dist/css/bootstrap.min.css';


const cairo = Cairo({ subsets: ["latin"], weight: ["300", "400", "700"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
      className={cairo.className}
>      

        <Header />
        <main className="className='lg:mb-[40px] pt-[111px] px-[24px] lg:px-[135px] flex min-h-screen flex-col  justify-between">
        {children}
        </main>
       

        <Footer />
      </body>
    </html>
  );
}
